services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false
        
    Kematjaya\BaseControllerBundle\Type\DateRangeType: ~
    Kematjaya\BaseControllerBundle\Type\AutoCompleteType: ~
    Kematjaya\BaseControllerBundle\Type\FloatRangeType: ~
